// Import and register all your controllers from the importmap via controllers/**/*_controller
import { application } from "controllers/application"
import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"



// This helper scans /controllers/**/*_controller.js and internally calls
// application.register("<identifier>", ControllerClass) for each one.
// This is a helper function that loads all controllers from the controllers directory.
eagerLoadControllersFrom("controllers", application)


// Shadcn-Rails controllers
//
// Note
// Prefer the “Rails importmap way” (no relative ./... imports)
// Import by module specifier using the “logical specifier” pattern used by importmap, and it lines up with the same idea as Sprockets logical asset paths
//
// Example:
//
// Instead of
// import ShadcnCombobox from "./shadcn/combobox_controller.js"
//
// Prefer
// import ShadcnCombobox from "controllers/shadcn/combobox_controller.js"
//
// "controllers/shadcn/combobox_controller" is a module specifier, not a filesystem path. The browser can’t resolve it by itself, so it consults the importmap.
// As this is not a filesystem path but a module specifier that is resolved via the importmap, not by the browser’s relative-path rules, you should omit .js.
// .js is already baked into the mapped URL
// Adding .js in the specifier would not match the importmap key (which is automatically generated by Rails without .js)
//
// If your config/importmap.rb has:
// pin_all_from "app/javascript/controllers", under: "controllers"
//
// Rails will generate an importmap entry like:
// "controllers/shadcn/combobox_controller": "/assets/controllers/shadcn/combobox_controller-<digest>.js"
//
// So the browser turns the specifier into a real URL and fetches it.
// Use importmap specifier instead of relative path for production compatibility
import ShadcnCombobox from "controllers/shadcn/combobox_controller"
application.register("shadcn--combobox", ShadcnCombobox)
